grasp_planning_node:
  ros__parameters:
    grasp_output_topic: "/grasp_tasks"
    easy_perception_deployment:
      epd_enabled: true
      tracking_enabled: false
      epd_topic: "/processor/epd_localize_output"
    camera_parameters:
      point_cloud_topic: "/camera/pointcloud"
      camera_frame: "camera_color_optical_frame"
    point_cloud_params:
      passthrough_filter_limits_x: [-0.50, 0.50]
      passthrough_filter_limits_y: [-0.15, 0.40]
      passthrough_filter_limits_z: [0.01, 0.70]      
      segmentation_max_iterations: 50
      segmentation_distance_threshold: 0.01
      cluster_tolerance: 0.01
      min_cluster_size: 750
      cloud_normal_radius: 0.03
      fcl_voxel_size: 0.02
    end_effectors:
      end_effector_names: [robotiq_2f, suction_cup]
      robotiq_2f:
        type: finger
        num_fingers_side_1: 2
        num_fingers_side_2: 2
        distance_between_fingers_1: 0.04
        distance_between_fingers_2: 0.04
        finger_thickness: 0.02
        gripper_stroke: 0.105
        grasp_planning_params:
          grasp_plane_dist_limit: 0.007
          voxel_size: 0.01
          grasp_rank_weight_1: 1.5
          grasp_rank_weight_2: 1.0
          world_x_angle_threshold: 0.5
          world_y_angle_threshold: 0.5
          world_z_angle_threshold: 0.25
      suction_cup:
        type: suction
        num_cups_length: 2
        num_cups_breadth: 2
        dist_between_cups_length: 0.06
        dist_between_cups_breadth: 0.03
        cup_radius: 0.01
        cup_height: 0.01
        grasp_planning_params:
          num_sample_along_axis: 3
          search_resolution: 0.01
          search_angle_resolution: 4
          weights:
            curvature: 1.0
            grasp_distance_to_center: 1.0
            number_contact_points: 1.0
      
