# Build only merge request and default branch.
# save time for quick demo pushes
include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

# Build with moveit
nightly:
  image:
    name: registry.gitlab.com/rosi-ap/rosi-ap_infrastructure/rosiap_docker_images/ros:moveit-rolling-nightly

  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .ccache/

  before_script:
    - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master

  variables:
    ISOLATION: "shell"
    ROS_DISTRO: "rolling"
    ROS_REPO: "main"
    CCACHE_DIR: "${CI_PROJECT_DIR}/.ccache"

  script:
    - .industrial_ci/gitlab.sh

foxy-coverage:
  image:
    name: ubuntu:20.04

  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .ccache/

  variables:
    ISOLATION: "shell"
    ROS_DISTRO: "foxy"
    CCACHE_DIR: "${CI_PROJECT_DIR}/.ccache"
    TARGET_CMAKE_ARGS: "-DCMAKE_C_FLAGS='--coverage' -DCMAKE_CXX_FLAGS='--coverage'"

  script:
    - apt-get update && apt-get install -y git
    - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
    - .industrial_ci/gitlab.sh

  after_script:
    - ./coverage.sh ci
    - bash <(curl -s https://codecov.io/bash) -f ./coverage.info

galactic-testing:
  image:
    name: ubuntu:20.04

  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .ccache/

  variables:
    ISOLATION: "shell"
    ROS_DISTRO: "galactic"
    CCACHE_DIR: "${CI_PROJECT_DIR}/.ccache"

  script:
    - apt-get update && apt-get install -y git
    - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
    - .industrial_ci/gitlab.sh

rolling:
  image:
    name: ubuntu:20.04

  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .ccache/

  variables:
    ISOLATION: "shell"
    ROS_DISTRO: "rolling"
    CCACHE_DIR: "${CI_PROJECT_DIR}/.ccache"

  script:
    - apt-get update && apt-get install -y git
    - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
    - .industrial_ci/gitlab.sh
